#!/usr/bin/env node

import path from 'node:path';
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';

import AE from './index.js';
import yargs from 'yargs';
import { hideBin } from 'yargs/helpers';

const argv = yargs(hideBin(process.argv))
	.usage('Usage: $0 filename')
	.alias('t', 'timing')
	.describe('t', 'Get timing information')
	.demandCommand(1)
	.help()
	.argv;

try {
	const programPath = path.resolve('.', argv._[0]);
	const cards = fs.readFileSync(programPath, {
		encoding: "utf8"
	});

	var eng = new AE.Interface();
	eng.submitProgram(cards, {
		sourceName: argv._[0].toString(),
		sourceUri: pathToFileURL(programPath).toString()
	});
	eng.runToCompletion();

	if (argv.t) {
		eng.attendant.traceLog(eng.timing.report());
	}

	console.log(`Attendant's Log:\n${eng.annunciator.L_output}\n`);
	console.log(`Printer:\n${eng.printer.O_output}\n`);
	console.log(`Curve Drawing Apparatus:\n${eng.curveDrawingApparatus.printScreen()}`);
} catch (e) {
	console.error(`Could not read file due to error: ${e}`);
}
